In [1]:
import warnings

warnings.filterwarnings(
    action="ignore",
    message=r"When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas\. Pass `\(name,\)` instead of `name` to silence this warning\.",
    category=FutureWarning,
    module=r"plotly\.express\._core",
)

# **IRIS FLOWER CLASSIFICATION**

**1. Importing Libraries**

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

**2. Load Dataset**

In [3]:
iris=pd.read_csv('/kaggle/input/iris-flower-dataset/IRIS.csv')
iris.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

**3. EDA**

In [4]:
iris.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [5]:
print("Target Labels",iris['species'].unique())

Target Labels ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [6]:
fig=px.scatter(data_frame=iris,x='petal_width',y='petal_length',color='species')
fig.show()

In [7]:
fig=px.scatter(data_frame=iris,x='sepal_width',y='sepal_length',color='species')
fig.show()

**Split the Testing and Training sets**

In [8]:
x=iris.drop('species',axis=1)
y=iris['species']

xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.6,random_state=1)

**Load the KNN Model and Train it**

In [9]:
knnModel=KNeighborsClassifier(n_neighbors=14)
knnModel.fit(xtrain,ytrain)

KNeighborsClassifier(n_neighbors=14)

**Test the KNN Model**

In [10]:
ypredict=knnModel.predict(xtest)

**Evaluation and Results**

> **Confusion Matrix**

In [11]:
confmat=confusion_matrix(ytest,ypredict)
print("Confusion Matrix :\n\n",confmat)

Confusion Matrix :

 [[30  0  0]
 [ 0 28  0]
 [ 0  4 28]]


> **Accuracy**

In [12]:
acc=accuracy_score(ytest,ypredict)
print("Accuracy : {}%".format(round(acc*100,2)))

Accuracy : 95.56%


> **Classification Report**

In [13]:
rep=classification_report(ytest,ypredict)
print(rep)

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        30
Iris-versicolor       0.88      1.00      0.93        28
 Iris-virginica       1.00      0.88      0.93        32

       accuracy                           0.96        90
      macro avg       0.96      0.96      0.96        90
   weighted avg       0.96      0.96      0.96        90

